common:
  env: tst
  replicas: 1

configMap:
  blobstoreProjectId: ent-irkalla-tst
  pubsubProjectId: ent-irkalla-tst
  nabuPubsubProjectId: ent-nabu-tst
  chouetteUrl: http://chouette.tst.entur.internal
  tiamatUrl: http://tiamat.tst.entur.internal

  auth0:
    ror:
      url: https://ror-entur-staging.eu.auth0.com/
      audience: https://ror.api.staging.entur.io
  blobstoreName: ror-irkalla-tst
  kafka:
    brokers: entur-kafka-test-ext-entur-test.aivencloud.com:11877
    registry: https://entur-kafka-test-ext-entur-test.aivencloud.com:11867
    topicUpdatedStopPlaces: ror-stop-place-changelog-staging
    secProtocol: SASL_SSL
    saslMechanism: SCRAM-SHA-512
