common:
  app: irkalla
  shortname: irkalla
  team: ror
  ingress:
    enabled: false
  service:
    internalPort: 8080
  container:
    image: ${artifact.metadata.image}
    cpu: 0.1
    memory: 750
    cpuLimit: 600m
    memoryLimit: 1100
    probes:
      liveness:
        path: /actuator/health/liveness
      readiness:
        path: /actuator/health/readiness
    envFrom:
      - secretRef:
          name: ror-irkalla-secrets
    prometheus:
      enabled: true
      path: /actuator/prometheus
    volumeMounts:
      - mountPath: /etc/application-config
        name: application-config
        readOnly: true
    volumes:
      - configMap:
          defaultMode: 420
          name: irkalla-application
        name: application-config
  postgres:
    enabled: false
  configmap:
    data:
      JDK_JAVA_OPTIONS: -server -Xmx950m -Dspring.config.location=/etc/application-config/application.properties -Dfile.encoding=UTF-8
      TZ: Europe/Oslo
    enabled: true
    toEnv: true