common:
  env: dev
  replicas: 1

configMap:
  blobstoreProjectId: ent-irkalla-dev
  pubsubProjectId: ent-irkalla-dev
  nabuPubsubProjectId: ent-nabu-dev
  chouetteUrl: http://chouette.dev.entur.internal
  tiamatUrl: http://tiamat.dev.entur.internal

  auth0:
    ror:
      url: https://ror-entur-dev.eu.auth0.com/
      audience: https://ror.api.dev.entur.io
  blobstoreName: ror-irkalla-dev
  kafka:
    brokers: entur-kafka-test-ext-entur-test.aivencloud.com:11877
    registry: https://entur-kafka-test-ext-entur-test.aivencloud.com:11867
    topicUpdatedStopPlaces: ror-stop-place-changelog-dev
    secProtocol: SASL_SSL
    saslMechanism: SCRAM-SHA-512
