apiVersion: v1
data:
  application.properties: |-
    spring.profiles.active=gcs-blobstore
    server.port={{ .Values.service.http.internalPort }}
    camel.component.servlet.mapping.context-path=/services/*
    camel.springboot.name=Irkalla

    # Chouette
    chouette.url={{ .Values.configMap.chouetteUrl }}
    chouette.sync.stop.place.full.cron=0 30 23 ? * SAT *
    chouette.sync.stop.place.cron=0 0/5 * * * ?
    chouette.sync.stop.place.autoStartup=true

    # Tiamat
    tiamat.url={{ .Values.configMap.tiamatUrl }}

    #OAuth2 Resource Server
    spring.security.oauth2.resourceserver.jwt.issuer-uri={{ .Values.configMap.auth0.ror.url }}
    irkalla.oauth2.resourceserver.auth0.ror.jwt.audience={{ .Values.configMap.auth0.ror.audience }}
    irkalla.oauth2.resourceserver.auth0.ror.claim.namespace=https://ror.entur.io/

    # Blobstore
    blobstore.gcs.project.id={{ .Values.configMap.blobstoreProjectId }}
    blobstore.gcs.credential.path=/etc/irkalla-service-account/credentials.json
    blobstore.gcs.container.name={{ .Values.configMap.blobstoreName }}

    # PubSub
    spring.cloud.gcp.pubsub.project-id={{ .Values.configMap.pubsubProjectId }}
    spring.cloud.gcp.pubsub.credentials.location=file:/etc/irkalla-service-account/credentials.json
    spring.cloud.gcp.pubsub.subscriber.parallel-pull-count=1
    spring.cloud.gcp.pubsub.subscriber.executor-threads=5
    spring.cloud.gcp.pubsub.subscriber.max-ack-extension-period=36000
    entur.pubsub.subscriber.autocreate=false

    # Spring Actuator
    management.server.port={{ .Values.service.http.managementPort }}
    management.endpoints.enabled-by-default=false
    management.endpoint.info.enabled=true
    management.endpoint.health.enabled=true
    management.endpoint.health.group.readiness.include=readinessState,pubSub
    management.endpoint.prometheus.enabled=true
    management.endpoints.web.exposure.include=info,health,prometheus

    spring.jackson.serialization.write-dates-as-timestamps=false
    etcd.url=http://etcd-client:2379
    # disable local redelivery to force Camel routes to be retried entirely.
    # this prevents a local retry from sending inconsistent requests to chouette
    irkalla.camel.redelivery.max=0

kind: ConfigMap
metadata:
  name: {{ template "irkalla.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
