common:
  env: prd
  replicas: 1

configMap:
  blobstoreProjectId: ent-irkalla-prd
  pubsubProjectId: ent-irkalla-prd
  nabuPubsubProjectId: ent-nabu-prd
  chouetteUrl: http://chouette.prd.entur.internal
  tiamatUrl: http://tiamat.prd.entur.internal

  auth0:
    ror:
      url: https://auth2.entur.org/
      audience: https://ror.api.entur.io
  blobstoreName: ror-irkalla-prd
  kafka:
    brokers: entur-kafka-prod-ext-entur-prod.aivencloud.com:14019
    registry: https://entur-kafka-prod-ext-entur-prod.aivencloud.com:14009
    topicUpdatedStopPlaces: ror-stop-place-changelog-production
    secProtocol: SASL_SSL
    saslMechanism: SCRAM-SHA-512
