env: dev

replicas: 1

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0
image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always
resources:
  cpuLimit: 600m
  memLimit: 1100Mi
  cpuRequest: 100m
  memRequest: 750Mi
  xmx: 950m

service:
  http:
    externalPort: 80
    internalPort: 8080
    managementPort: 9001

configMap:
  kafka:
    enabled: false
    secProtocol: SASL_SSL
    saslMechanism: SCRAM-SHA-512
    username: ${KAFKA_USERNAME}
    password: ${KAFKA_PASSWORD}

rbac:
  enabled: false