common:
  app: irkalla
  shortname: irkalla
  team: ror
  ingress:
    enabled: false
  service:
    internalPort: 8080
  container:
    image: <+artifacts.primary.image>
    cpu: 0.1
    memory: 750
    memoryLimit: 1100
    probes:
      liveness:
        path: /actuator/health/liveness
      readiness:
        path: /actuator/health/readiness
    prometheus:
      enabled: true
      path: /actuator/prometheus
    volumeMounts:
      - mountPath: /etc/application-config
        name: application-config
        readOnly: true
    volumes:
      - configMap:
          defaultMode: 420
          name: irkalla-application
        name: application-config
  postgres:
    enabled: false
  configmap:
    data:
      JDK_JAVA_OPTIONS: -server -Xmx950m -Dspring.config.location=/etc/application-config/application.properties -Dfile.encoding=UTF-8
      TZ: Europe/Oslo
    enabled: true
    toEnv: true
  secrets:
    ror-irkalla-secrets: [KAFKAPASSWORD, KAFKAUSERNAME]
