configMap:
  blobstoreProjectId: entur-ror-test
  pubsubProjectId: entur-ror-test
  keycloak:
    url:  https://kc-stage.devstage.entur.io/auth
  auth0:
    ror:
      url: https://ror-entur-staging.eu.auth0.com/
      audience: https://ror.api.staging.entur.io
  blobstoreName: irkalla-test

rbac:
  enabled: true

