configMap:
  blobstoreProjectId: entur-ror-prod
  pubsubProjectId: entur-ror-prod
  keycloak:
    url:  https://auth.entur.org/auth
  auth0:
    ror:
      url: https://auth2.entur.org/
      audience: https://ror.api.entur.io
  blobstoreName: irkalla-production
rbac:
  enabled: true