configMap:
  blobstoreProjectId: entur-ror-dev
  pubsubProjectId: entur-ror-dev
  keycloak:
    url: https://kc-dev.devstage.entur.io/auth
  auth0:
    ror:
      url: https://ror-entur-dev.eu.auth0.com/
      audience: https://ror.api.dev.entur.io
  blobstoreName: irkalla-dev
rbac:
  enabled: true