name: Build and push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  docker-lint:
    uses: entur/gha-docker/.github/workflows/lint.yml@v1
  maven-verify:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21.0.1+12
          distribution: liberica
          cache: 'maven'
        env:
          GITHUB_ACTOR: ${{ secrets.ARTIFACTORY_USER }}
          GITHUB_TOKEN: ${{ secrets.ARTIFACTORY_APIKEY }}
      - run: |
          echo "export JFROG_USER=$ARTIFACTORY_USER"  >> $BASH_ENV
          echo "export JFROG_PASS=$ARTIFACTORY_PASSWORD"  >> $BASH_ENV
          echo "$ARTIFACTORY_SETTINGS" | base64 --decode > .github/settings.xml
          mvn verify -s .github/settings.xml
      - uses: actions/upload-artifact@v4.3.3
        with:
          path: target/*.jar
  docker-build:
    needs: [docker-lint, maven-verify]
    uses: entur/gha-docker/.github/workflows/build.yml@v1
    with:
      build_artifact_name: artifact
      build_artifact_path: target
  docker-push:
    if: github.repository_owner == 'entur' && github.event_name == 'push'
    needs: [docker-build]
    uses: entur/gha-docker/.github/workflows/push.yml@v1